export enum CategoryType {
  FARM = "FARM",
  GARDEN = "GARDEN",
  RESTAURANT = "RESTAURANT",
  CAFE = "CAFE",
  BAR = "BAR",
  MARKET = "MARKET",
  SPORTS = "SPORTS",
  CULTURE = "CULTURE",
  NATURE = "NATURE",
  ENTERTAINMENT = "ENTERTAINMENT",
  EDUCATION = "EDUCATION",
  WELLNESS = "WELLNESS",
  FAMILY = "FAMILY",
  ADVENTURE = "ADVENTURE",
  MUSIC = "MUSIC",
  ART = "ART",
  FESTIVAL = "FESTIVAL",
  SHOPPING = "SHOPPING",
  NIGHTLIFE = "NIGHTLIFE",
  OTHER = "OTHER",
}

export const CategoryTypeLabels: Record<CategoryType, string> = {
  [CategoryType.FARM]: "Farm",
  [CategoryType.GARDEN]: "Garden",
  [CategoryType.RESTAURANT]: "Restaurant",
  [CategoryType.CAFE]: "Cafe",
  [CategoryType.BAR]: "Bar",
  [CategoryType.MARKET]: "Market",
  [CategoryType.SPORTS]: "Sports",
  [CategoryType.CULTURE]: "Culture",
  [CategoryType.NATURE]: "Nature",
  [CategoryType.ENTERTAINMENT]: "Entertainment",
  [CategoryType.EDUCATION]: "Education",
  [CategoryType.WELLNESS]: "Wellness",
  [CategoryType.FAMILY]: "Family",
  [CategoryType.ADVENTURE]: "Adventure",
  [CategoryType.MUSIC]: "Music",
  [CategoryType.ART]: "Art",
  [CategoryType.FESTIVAL]: "Festival",
  [CategoryType.SHOPPING]: "Shopping",
  [CategoryType.NIGHTLIFE]: "Nightlife",
  [CategoryType.OTHER]: "Other",
};
